// eslint-disable-next-line no-unused-vars
const sections = [
    {id: 1, name:'Rachunek zbiorów i logika', subsubsections: [
      {id: 19, name:'Znaczenie zbiorów na osi liczbowej', site:"https://www.matemaks.pl/zaznaczanie-zbiorow-na-osi-liczbowej.html"},
      {id: 20, name:'Suma zbiorów', site: "https://www.matemaks.pl/suma-zbiorow.html"},
      {id: 21, name:'Róznica zbiorów', site:"https://www.matemaks.pl/roznica-zbiorow.html"},
      {id: 22, name:'Iloczyn zbiorów', site:"https://www.matemaks.pl/iloczyn-zbiorow.html"},
      {id: 23, name:'Logika', subsubsections: [
        {id: 24, name:'Wprowadzenie do logiki matematycznej', site: "https://www.matemaks.pl/logika.html"},
        {id: 25, name:'Zdania logiczne', site: "https://www.matemaks.pl/zdania-logiczne.html"},
        {id: 26, name:'Koniuunkcja', site: "https://www.matemaks.pl/koniunkcja.html"},
        {id: 27, name:'Alternatywa', site:"https://www.matemaks.pl/alternatywa.html"},
        {id: 28, name:'Implikacja', site: "https://www.matemaks.pl/implikacja.html"},
        {id: 29, name:'Równoważność', site: "https://www.matemaks.pl/rownowaznosc.html"},
        {id: 30, name:'Negacja', site: "https://www.matemaks.pl/negacja.html"},
        {id: 31, name:'Warunek konieczny i wystarczający', site: "https://www.matemaks.pl/warunek-konieczny-i-warunek-wystarczajacy.html"},
        {id: 32, name:'Prawa rachunku zdań', subsubsections: [
          {id: 33, name:'Prawa rachunku zdań - definicja i najważniejsze wzory', site: "https://www.matemaks.pl/prawa-rachunku-zdan.html"},
          {id: 34, name:'Metoda zero-jedynkowa dowodzenia tauutologii', site: "https://www.matemaks.pl/metoda-zero-jedynkowa-dowodzenia-tautologii.html"},
          {id: 35, name:'Prawo wyłączonego środka', site: "https://www.matemaks.pl/prawo-wylaczonego-srodka.html"},
          {id: 36, name:'Prawo sprzeczności', site:"https://www.matemaks.pl/prawo-sprzecznosci.html"},
          {id: 37, name:'Prawo podwójnej negacji', site:"https://www.matemaks.pl/prawo-podwojnej-negacji.html"},
          {id: 38, name:'1 prawo de Morgana', site:"https://www.matemaks.pl/i-prawo-de-morgana.html"},
          {id: 39, name:'2 prawo de Morgana', site: "https://www.matemaks.pl/ii-prawo-de-morgana.html"},
          {id: 40, name:'Prawo odkrywania', site:"https://www.matemaks.pl/prawo-odrywania.html"},
          {id: 41, name:'Prawo negacji implikacji', site:"https://www.matemaks.pl/prawo-negacji-implikacji.html"},
          {id: 42, name:'Prawo rozdzielności koniunkcji względem alternatywy', site:"https://www.matemaks.pl/prawo-rozdzielnosci-koniunkcji-wzgledem-alternatywy.html"},
          {id: 43, name:'Prawo rozdzielności alternatywy względem koniunkcji', site:"https://www.matemaks.pl/prawo-rozdzielnosci-alternatywy-wzgledem-koniunkcji.html"} 
        ]},
        {id: 44, name:'Kwalifikatory', site:"https://www.matemaks.pl/kwantyfikatory.html"}
      ]},
    ]},
    {id: 2, name:'Wartość bezwzględna', subsubsections: [
      {id: 45, name:'Definicja wartości bezwzględnej', site:"https://www.matemaks.pl/wartosc-bezwzgledna.html"},
      {id: 46, name:'Wartość bezwzględna wyrażeń z x-em', site: "https://www.matemaks.pl/wartosc-bezwzgledna-wyrazen-z-x-em.html"},
      {id: 47, name:'Wykres wartości bezwzględnej', site:"https://www.matemaks.pl/wykres-wartosci-bezwzglednej.html"},
      {id: 48, name:'Interpretacja geometryczna wartości bezwzględnej', site:"https://www.matemaks.pl/interpretacja-geometryczna-wartosci-bezwzglednej.html"},
      {id: 49, name:'Rownania z wartością bezwzględną', site:"https://www.matemaks.pl/rownania-z-wartoscia-bezwzgledna.html"},
      {id: 50, name:'Nierówności z wartością bezwzględną', site:"https://www.matemaks.pl/nierownosci-z-wartoscia-bezwzgledna.html"},
      {id: 51, name:'Równania z kilkoma wartościami bezwzględnymi', site:"https://www.matemaks.pl/rownania-z-kilkoma-wartosciami-bezwzglednymi.html"},
      {id: 52, name:'Nierówności z więcej niż jedną wartością bezwzględną', site:"https://www.matemaks.pl/nierownosci-z-wiecej-niz-jedna-wartoscia-bezwzgledna.html"},
    ]},
    {id: 3, name:'Logarytmy', subsubsections: [
      {id: 53, name:'Wprowadzenie do logarytmów', site:"https://www.matemaks.pl/logarytmy.html"},
      {id: 54, name:'Logarytmy - najważniejsze wzory', site:"https://www.matemaks.pl/logarytmy-najwazniejsze-wzory.html"},
      {id: 55, name:'Obliczanie logarytmów', site:"https://www.matemaks.pl/obliczanie-logarytmow.html"},
      {id: 56, name:'Dodawanie i odejmowanie logarytmów', site: "https://www.matemaks.pl/dodawanie-i-odejmowanie-logarytmow.html"},
      {id: 57, name:'Logarytmy o wykładniku potęgi', site: "https://www.matemaks.pl/logarytm-w-wykladniku-potegi.html"},
      {id: 58, name:'Równania logarytmiczne', site:"https://www.matemaks.pl/rownania-logarytmiczne.html"},
      {id: 59, name:'Różne zadania z logarytmów', site: "https://www.matemaks.pl/rozne-zadania-z-logarytmow.html"},
    ]},
    {id: 4, name:'Wyrażenia algebraiczne', subsubsections: [
      {id: 60, name:'Wprowadzenie do wyrażeń algebraicznych'},
      {id: 61, name:'Obliczanie wartości liczbowej wyrażenia algebraicznego'},
      {id: 62, name:'Jednomiany'},
      {id: 63, name:'Sumowanie wyrażeń algebraicznych'},
      {id: 64, name:'Mnożenie wyrażeń algebraicznych'},
      {id: 65, name:'Wzory skróconego mnożenia', subsubsections: [
        {id: 66, name:'Najważniejsze wzory skróconego mnożenia'},
        {id: 67, name:'Kwadrat sumy'},
        {id: 68, name:'Kwadrat różnicy'},
        {id: 69, name:'Różnica kwadratów'},
        {id: 70, name:'Sześcian szescianów'},
        {id: 71, name:'Suma sześcianów'},
        {id: 72, name:'Sześcian sumy'},
        {id: 73, name:'Sześcian różnicy'},
        {id: 74, name:'Zadania ze wzorów skróconego mnożenia'},
      ]},
      {id: 75, name:'Dwumian Newtona'},
      {id: 76, name:'Różne zadania z wyrażeń algebraicznych'},
    ]},

    {id: 5, name:'Równania i nierówności', subsubsections: [
        {id: 77, name:'Równania liniowe', subsubsections: [
            {id: 78, name:'Wprowadzenie do rówań liniowych'},
            {id: 79, name:'Zadania na rozwiązywanie równań'},
            {id: 80, name:'Równania tożsamościowe'},
            {id: 81, name:'Równania sprzeczne'},
            {id: 82, name:'Równania w zadanicha z treścią'},
        ]},
        {id: 83, name:'Równania oznaczone, tożsamościowe i sprzeczne'},
        {id: 84, name:'Nierówności liniowe'},
        {id: 85, name: 'Układy równań', subsubsections: [
            {id: 86, name:'Wprowadzenie do układów równań'},
            {id: 87, name:'Metoda podstawiania'},
            {id: 88, name:'Metoda przeciwnych współczynników'},
            {id: 89, name:'Metoda graficzna'},
            {id: 90, name:'Metoda wyznaczników'},
            {id: 91, name:'Układy oznaczone, nieoznaczone i sprzeczne'},
            {id: 92, name:'Układy równań w zadaniach z treścią'},
            {id: 93, name:'Rózne zadania z układów równań'},
        ]},
        {id: 94, name:'Równania kwadratowe', subsubsections: [
            {id: 95, name:'Wprowadzenie do równań kwadratowych'},
            {id: 96, name:'Proste równania kwadratowe'},
            {id: 97, name:'Równania kwadratowe w postaci ogólnej'},
            {id: 98, name:'Równania sprowadzalne do równań kwadratowych'},
            {id: 99, name:'Program do rozwiązywania równań kwadratowych'},
            {id: 100, name:'Zadania z równań kwadratowych'},
        ]},
        {id: 101, name:'Nierówności kwadratowe', subsubsections: [
            {id: 102, name:'Wstęp do nierówności kwadratowych'},
            {id: 103, name:'Metody rozwiązywania nierówności kwadratowych'},
            {id: 104, name:'Zadania na rozwiązywanie nierówności kwadratowych'},
        ]},
        {id: 105, name: 'Równania wykładnicze'},
        {id: 106, name: 'Nierówności wykładnicze'},
    ]},
    {id: 6, name:'Funkcje', subsubsections: [
        {id: 107, name: 'Funkcje - definicja i własności', subsubsections: [
            {id: 108, name: 'Wprowadzenie do funkcji - proste przykłady'},
            {id: 109, name: 'Definicja funkcji'},
            {id: 110, name: 'Sposoby prezetowania funkcji'},
            {id: 111, name: 'Wykres funkcji', subsubsections: [
                {id: 112, name: 'Jak rysować wykres funkcji'},
                {id: 113, name: 'Zmaienne niezależne i zmienne zależne'},
                {id: 114, name: 'Oś odciętych i oś rzędnych'},
                {id: 115, name: 'Zadania na rysowanie wykresów funkcji'},
            ]},
            {id: 116, name: 'Dziedzina funkcji'},
            {id: 117, name: 'Wartości funkcji i odczytywanie ich z wykresu'},
            {id: 118, name: 'Własności funkcji'},
            {id: 119, name: 'Miejsca zerowe funkcji'},
            {id: 120, name: 'Funkcje parzyste i nieparzyste'},
            {id: 121, name: 'Monotonność funkcji'},
            {id: 122, name: 'Przesunięcia wykresów funkcji'},
            {id: 123, name: 'Rózne zadania z funkcji'},
        ]},
        {id: 124, name: 'Funkcja liniowa', subsubsections: [
            {id: 125, name: 'Definicja funkcji liniowej'},
            {id: 126, name: 'Wykres funkcji liniowej'},
            {id: 127, name: 'Miejsce zerowe funkcji liniowej'},
            {id: 128, name: 'Funkcja liniowa - zadania z parametrem'},
            {id: 129, name: 'Inne zadania z funkcji liniowej'},
        ]},
        {id: 130, name: 'Funkcja kwadratowa', subsubsections: [
            {id: 131, name: 'Wprowadzenie do funkcji kwadratowej'},
            {id: 132, name: 'Wykres funkcji kwadratowej'},
            {id: 133, name: 'Miejsce zerowe funkcji kwadratowej'},
            {id: 134, name: 'Postać ogólna, kanoniczna i iloczynowa funkcji kwadratowej', subsubsections: [
                {id: 135, name: 'Wstęp do postaci funkcji kwadratowej'},
                {id: 136, name: 'Postać ogólna funkcji kwadratowej'},
                {id: 137, name: 'Postać kanoniczna funkcji kwadratowej'},
                {id: 138, name: 'Postać iloczynowa funkcji kwadratowej'},
                {id: 139, name: 'Zamiana postaci ogólnej na postać kanoniczną i iloczynową'},
                {id: 140, name: 'Zamiana postaci kanonicznej na postać ogólną i iloczynową'},
                {id: 141, name: 'Zamiana postaci iloczynowej na postać ogólną i kanoniczną'},
            ]},
            {id: 142, name: 'Oś symetrii paraboli'},
            {id: 143, name: 'Rózne zadania z funkcji kwadratowej'},
        ]},
        {id: 144, name: 'Funkcja wymierna', subsubsections: [
            {id: 145, name: 'Wprowadzenie do funkcji wymiernej'},
            {id: 146, name: 'Proporcjonalość odwrotna', subsubsections: [
                {id: 147, name: 'Wprowadzenie do proporcjonalności odwrotnej'},
                {id: 148, name: 'Wykres proporcjonalności odwrotnej'},
            ]},
            {id: 149, name: 'Definicja funkcji wymiernej'},
            {id: 150, name: 'Dziedzina funkcji wymiernej'},
        ]},
        {id: 151, name: 'Funkcja logarytmiczna', subsubsections: [
            {id: 152, name: 'Wprowadzenie do funkcji logarytmicznej'},
            {id: 153, name: 'Dziedzina funkcji logarytmicznej'},
            {id: 154, name: 'Rózne zadania z funkcji logarytmicznej'},
        ]},
        {id: 155, name: 'Funkcja wykładnicza', subsubsections: [
            {id: 156, name: 'Wprowadzenie do funkcji wykładniczej'},
            {id: 157, name: 'Różne zadania z funkcji wykładniczej'},
        ]}
    ]},
    {id: 7, name:'Wielomiany', subsubsections: [
        {id: 158, name: 'Wprowadzenie do wielomianów'},
        {id: 159, name: 'Obliczanie wartości wielomianu'},
        {id: 160, name: 'Stopień wielomianu'},
        {id: 161, name: 'Rozkład wielomianu na czynniki', subsubsections: [
            {id: 162, name: 'Wprowadzenie do rozkładu wielomianu na czynniki'},
            {id: 163, name: 'Podstawowe sposoby rozkładu wielomianu na czynniki'},
            {id: 164, name: 'Rozkład wielomianu na czynniki - zadania'},
        ]},
        {id: 165, name: 'Dodawanie i odejmowanie wielomianów'},
        {id: 166, name: 'Dzielenie wielomianów'},
        {id: 167, name: 'Równość wielomianów'},
        {id: 168, name: 'Równania wielomianowe', subsubsections: [
            {id: 169, name: 'Wprowadzenie do równań wielomianowych'},
            {id: 170, name: 'Metoda rozwiązywania równań wielomianowych'},
            {id: 171, name: 'Równania wielomianowe - zadania'},
        ]},
        {id: 172, name: 'Krotność pierwiastka wielomianu'},
        {id: 173, name: 'Twierdznie Bezouta'},
        {id: 174, name: 'Wymierne pierwiastki wielomianu o współczynnikach całkowitych'},
        {id: 175, name: 'Schemat Hornera'},
        {id: 176, name: 'Wykres wielomianu', subsubsections: [
            {id: 177, name: 'Wprowadzenie'},
            {id: 178, name: 'Metoda rysowania wykresu wielomianu'},
            {id: 179, name: 'Wykresy wielomianów - zadania'},
        ]},
        {id: 180, name: 'Nierówności wielomianowe', subsubsections: [
            {id: 181, name: 'Wprowadzenie'},
            {id: 182, name: 'Metoda rozwiązywania nierówności wielomianowych'},
            {id: 183, name: 'Nierówności wielomianowe - przykłady'},
        ]},
        {id: 184, name: 'Różne zadania z wielomianów'},
    ]},
    {id: 8, name:'Wyrażenia wymierne', subsubsections: [
        {id: 185, name: 'Podstawowe wiadomości o wyrażeniach wymiernych'},
        {id: 186, name: 'Dziedzina wyrażenia wymiernego'},
        {id: 187, name: 'Skracanie wyrażeń wymiernych'},
        {id: 188, name: 'Dodawanie i odejmowanie wyrażeń wymiernych'},
        {id: 189, name: 'Równania wymierne'},
        {id: 190, name: 'Różne zadania z wyrażeń wymiernych'},
    ]},
    {id: 9, name:'Ciągi liczbowe', subsubsections: [
        {id: 191, name: 'Wprowadzenie do ciągów'},
        {id: 192, name: 'Wzór ogólny ciągu'},
        {id: 193, name: 'Monotoniczność ciągu'},
        {id: 194, name: 'Ciąg arytmetyczny', subsubsections: [
            {id: 195, name: 'Definicja ciągu arytmetycznego i przykłady'},
            {id: 196, name: 'Wzór na n-ty wyraz ciągu arytmetycznego'},
            {id: 197, name: 'Suma ciągu arytmetycznego'},
            {id: 198, name: 'Różne zadania z ciągów arytmetycznych'},
        ]},
        {id: 199, name: 'Ciąg geometryczny', subsubsections: [
            {id: 200, name: 'Definicja ciągu geometrycznego i przykłady'},
            {id: 201, name: 'Wzór na n-ty wyraz ciągu geometrycznego'},
            {id: 202, name: 'Suma ciągu geometrycznego'},
            {id: 203, name: 'Różne zadania z ciągów geometrycznych'},
        ]},
        {id: 204, name: 'Granica ciągu liczbowego'},
        {id: 205, name: 'Różne zadania z ciągów'},
    ]},
    {id: 10, name:'Trygonometria', subsubsections: [
        {id: 206, name: 'Wprowadzenie do trygonometrii'},
        {id: 207, name: 'Wzory trygonometryczne'},
        {id: 208, name: 'Definicje funkcji trygonometrycznych w trójkącie prostokątnym'},
        {id: 209, name: 'Jedynka trygonometryczna oraz wzory na tangens i cotangens'},
        {id: 210, name: 'Obliczanie wartości funkcji trygonometrycznych'},
        {id: 211, name: 'Trójkąt prostokątny 30-60-90'},
        {id: 212, name: 'Trójkąt prostokątny 45-45-90'},
        {id: 213, name: 'Zależności trygonometryczne w trojkącie prostokątnym'},
        {id: 214, name: 'Praktyczne zastosowania podstaw trygonometrii'},
        {id: 215, name: 'Tablice wartości funkcji trygonometrycznych dla kątów ostrych'},
        {id: 216, name: 'Pojęcie miary kąta i jego uogólnienie'},
        {id: 217, name: 'Miara łukowa kąta'},
        {id: 218, name: 'Zamiana stopni na radiany'},
        {id: 219, name: 'Zamiana radianów na stopnie'},
        {id: 220, name: 'Funkcje trygonometryczne dowolonego kąta'},
        {id: 221, name: 'Obliczanie wartości funkcji trygonometrycznych dowolnego kąta'},
        {id: 222, name: 'Wykres funkcji sinus'},
        {id: 223, name: 'Wykresy funkcji trygonometrycznych - zestawienie'},
        {id: 224, name: 'Równania trygonometryczne'},
        {id: 225, name: 'Nierówności trygonometryczne'},
        {id: 226, name: 'Różne zadania z trygonometrii'},
    ]},
    {id: 11, name:'Wektory', subsubsections: [
        {id: 227, name: 'Podstawowa wiedza o wektorach'},
        {id: 228, name: 'Iloczyn skalarny wektorów'},
    ]},
    {id: 12, name:'Geometria analityczna', subsubsections: [
        {id: 229, name: 'Wstęp do geometrii analitycznej'},
        {id: 230, name: 'Długość odcinka w układzie współrzędnych'},
        {id: 231, name: 'Środek odcinka'},
        {id: 232, name: 'Równanie prostej przechodzącej przez dwa punkty'},
        {id: 233, name: 'Proste równoległe i prostopadłe'},
        {id: 234, name: 'Proste równoległe/prostopadłe przechodzące przez dany punkt'},
        {id: 235, name: 'Odległość punktu od prostej'},
        {id: 236, name: 'Równanie okręgu'},
        {id: 237, name: 'Różne zadania z geometrii analitycznej'},
    ]},
    {id: 13, name:'Geometria płaska', subsubsections: [
        {id: 238, name: 'Definicje róznych pojęć geometrycznych'},
        {id: 239, name: 'Prosta, półprosta i odcinek'},
        {id: 240, name: 'Kąt ostry, prosty, rozwarty, wklesły, wypukły, półpełny i pełny'},
        {id: 241, name: 'Kąt wypukły i wklesły'},
        {id: 242, name: 'Kąty wierzchołkowe, przyległe, odpowiadające i naprzemianległe'},
        {id: 243, name: 'Trójkąt'},
        {id: 244, name: 'Wzory na pole trójkąta'},
        {id: 245, name: 'Suma kątów wewnętrznych trójkąta'},
        {id: 246, name: 'Trójkąt równoboczny'},
        {id: 247, name: 'Trójkąt prostokątny'},
        {id: 248, name: 'Twierdzenie Pitagorasa'},
        {id: 249, name: 'Okrąg opisany na trójkącie prostokątnym'},
        {id: 250, name: 'Okrąg wpisany w trójkąt prostokątny'},
        {id: 251, name: 'Podobieństwo trójkątów'},
        {id: 252, name: 'Twierdzenie Talesa'},
        {id: 253, name: 'Rózne zadania z trójkątów'},
        {id: 254, name: 'Czworokąt'},
        {id: 255, name: 'Kwadrat'},
        {id: 256, name: 'Równoległobok'},
        {id: 257, name: 'Romb'},
        {id: 258, name: 'Trapez'},
        {id: 259, name: 'Deltoid'},
        {id: 260, name: 'Okrąg i koło'},
        {id: 261, name: 'Kąty środkowe i wpisane w okręgu'},
        {id: 262, name: 'Okrąg wpisany w trójkat'},
        {id: 263, name: 'Okrąg opisany na trójkącie'},
        {id: 264, name: 'Czworokąt wpisany w okrąg'},
        {id: 265, name: 'Rózne zadania z okręgu i koła'},
        {id: 266, name: 'Twierdzenie sinusów'},
        {id: 267, name: 'Twierdzenie cosinusów'},
        {id: 268, name: 'Rózne zadania z geometrii'},
    ]},
    {id: 14, name:'Geometria przestrzenna', subsubsections: [
        {id: 269, name: 'Graniastosłupy', subsubsections: [
            {id: 270, name: 'Definicja graniastosłupa'},
            {id: 271, name: 'Prostopadłościan'},
            {id: 272, name: 'Sześcian'},
            {id: 273, name: 'Rózne zadania z graniastosłupów'},
        ]},
        {id: 274, name: 'Ostrosłupy', subsubsections: [
            {id: 275, name: 'Definicja ostrosłupa'},
            {id: 276, name: 'Ostrosłup prawidłowy czworokątny'},
            {id: 277, name: 'Ostrosłup prawidłowy trójkątny'},
            {id: 278, name: 'Czworościan foremny'},
            {id: 279, name: 'Rózne zadania z ostrosłupów'},
        ]},
        {id: 280, name: 'Bryły obrotowe', subsubsections: [
            {id: 281, name: 'Definicja bryły obrotowej'},
            {id: 282, name: 'Walec'},
            {id: 283, name: 'Stożek'},
            {id: 284, name: 'Kula'},
        ]}
    ]},
    {id: 15, name:'Kombinatoryka', subsubsections: [
        {id: 285, name: 'Wprowadzenie do kombinatoryki'},
        {id: 286, name: 'Reguła mnożenia'},
        {id: 287, name: 'Silnia', subsubsections: [
            {id: 288, name: 'Definicja silni i przykłady'},
            {id: 289, name: 'Program do liczenia silni'},
            {id: 290, name: 'Zadania z silni'},
        ]},
        {id: 291, name: 'Kombinacja'},
        {id: 292, name: 'Permutacja'},
        {id: 293, name: 'Warjańcja z powtórzeniami'},
        {id: 294, name: 'Warjańcja bez powtórzeń'},
        {id: 295, name: 'Rózne zadania z kombinatoryki'},
    ]},
    {id: 16, name:'Rachunek prawdopodobieństwa', subsubsections: [
        {id: 296, name: 'Wprowadzenie do rachunku prawdopodobieństwa'},
        {id: 297, name: 'Wzory i własności w rachunku prawdopodobieństwa'},
        {id: 298, name: 'Zadania z klasycznego rachunku prawdopodobieństwa'},
        {id: 299, name: 'Własności rachunku prawdopodobieństwa'},
        {id: 300, name: 'Prawdoopodobieństwo warunkowe'},
        {id: 301, name: 'Prawdopodoieństwo całkowite'},
    ]},
    {id: 17, name:'Statystyka', subsubsections: [
        {id: 302, name: 'Średnia arytmetyczna'},
        {id: 303, name: 'Błąd bezwzględny i względny pomiaru'},
        {id: 304, name: 'Średnia ważona'},
        {id: 305, name: 'Odchylenie'},
        {id: 306, name: 'Wariancja'},
        {id: 307, name: 'Odchylenie standardowe'},
        {id: 308, name: 'Mediana'},
        {id: 309, name: 'Moda'},
        {id: 310, name: 'Rózne zadania z statystyki'},
    ]},
    {id: 18, name:'Elementy analizy matematycznej', subsubsections: [
        {id: 311, name: 'Wprowadzenie'},
        {id: 312, name: 'Granica funkcji w punkcie'},
        {id: 313, name: 'Granice jednostronne funkcji'},
        {id: 314, name: 'Granica funkcji w nieskończoności'},
        {id: 315, name: 'Styczna do wykresu funkcji'},
        {id: 316, name: 'Badanie monotoniczności funkcji za pomocą pochodnej'},
        {id: 317, name: 'Ekstrema lokalne funkcji'},
        {id: 318, name: 'Największa i najmniejsza wartość funkcji w przedziale'},
        {id: 319, name: 'Badanie przebiegu zmienności funkcji'},
        {id: 320, name: 'Zadania optymalizacyjne'},
    ]}
  ];
/*ZAKRES STUDENCKI SIE NA RAZIE NIE ZMIEŚCIŁ :P*/
  export default sections;